### ISSUE TITLE
Rootless not Working

### ISSUE THREAD

**Issue by AriyanYT** [cs59/Dylib-to-Deb-Converter#1]
After patching rootless jb deb file not working for targeted bundle id, but rootful patch working after patched in Dopamine  Deerootifier

Deb file installation location is wrong
/var/jb/var/Library/MobileSubstrate/DynamicLibraries

Need this location for Dopamine
/var/jb/Library/MobileSubstrate/DynamicLibraries

Plz added multiple targets Bundle ID

**Comment by cs59** [comment]
Thank you for mentioning errors and problems in this script. I will fix all this problems and will also add support to enter multiple bundle id’s.

Don’t hesitate to mention other bugs too if found, feel free to report bugs.
